name: quiet
description: a music player
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.3
  json_annotation: any
  dio: 4.0.0
  dio_cookie_manager: 2.0.0
  path_provider: ^2.0.2
  shared_preferences: ^2.0.6
  video_player: ^2.1.10
  url_launcher: ^6.0.9
  intl: ^0.17.0
  sembast: ^3.1.0+2
  scoped_model: ^2.0.0-nullsafety.0
  loader:
    git:
      url: https://github.com/jiangxiaoqiang/loader.git
      ref: e1ef2d9957bc8615c7f19f989d4fcfc142e20e93
  encrypt: ^5.0.0
  netease_music_api:
    git:
      url: https://github.com/jiangxiaoqiang/NeteaseCloudMusicApi.git
      ref: 851c3fab0638881b39f7094b0c98bedd98192a44
  overlay_support: ^1.2.1
  music_player:
    git:
      url: https://github.com/jiangxiaoqiang/flutter-music-player.git
  provider: ^5.0.0
  scrollable_positioned_list: ^0.2.0-nullsafety.0
  hive: ^2.0.4
  hooks_riverpod: 1.0.0-dev.6
  riverpod: 1.0.0-dev.6
  flutter_json_view: ^0.2.1
  flutter_hooks: ^0.18.0
  wheel:
    git:
      url: https://github.com/jiangxiaoqiang/wheel.git
      ref: main
  get: 4.3.8
  sqflite: 2.0.0+4

dependency_overrides:
  flutter_secure_storage: 4.2.1
  platform: ^3.1.0
  collection: ^1.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.6
  mockito: ^5.0.11
  lint: ^1.5.3
  json_serializable: any

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/cfg/

flutter_intl:
  enabled: true
